apiVersion: v2
name: stack-auth
description: A Helm chart to deploy the Stack Auth platform. https://stack-auth.com
type: application
version: 0.6.0

dependencies:
  # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/Chart.yaml
  - name: postgresql
    version: 15.5.34
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: svix
    version: 0.4.0
    repository: https://jshimko.github.io/helm-charts
    condition: svix.enabled
