apiVersion: v2
name: stack-auth
description: A Helm chart to deploy the Stack Auth platform. https://stack-auth.com
type: application
version: 0.10.1

dependencies:
  # Postgres Operator - PostgresCluster
  # https://access.crunchydata.com/documentation/postgres-operator/latest/
  - name: postgrescluster
    version: 5.6.2
    repository: https://jshimko.github.io/helm-charts
    condition: postgrescluster.enabled

  # Svix webhooks
  # https://github.com/jshimko/helm-charts/tree/main/charts/svix
  - name: svix
    version: 0.8.1
    repository: https://jshimko.github.io/helm-charts
    condition: svix.enabled
