# Default values for stack-auth.

nameOverride: ""
fullnameOverride: ""

# Explicitly manage the namespace.
# This is useful when using ArgoCD to manage the release because deleting
# the chart deployment will then also clean up the namespace when enabled.
manageNamespace:
  enabled: false

# Dashboard
dashboard:
  replicaCount: 1

  image:
    repository: jshimko/stack-dashboard
    pullPolicy: IfNotPresent
    tag: dev

  imagePullSecrets: []

  # -- Dashboard environment variables - see available [.env](https://github.com/stack-auth/stack/blob/dev/apps/dashboard/.env) options
  env:
    []
    # - name: NODE_ENV
    #   value: production

  # -- Dashboard environment variables from secrets or configmaps
  envFrom:
    []
    # - secretRef:
    #     name: my-secret
    # - configMapRef:
    #     name: my-configmap

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Automatically mount a ServiceAccount's API credentials?
    automount: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is stack-dashboard
    name: ""

  podAnnotations: {}
  podLabels: {}

  podSecurityContext:
    {}
    # fsGroup: 2000

  securityContext:
    {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 8101

  ingress:
    enabled: false
    className: ""
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - example.com

  # -- https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources:
    {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  startupProbe:
    # httpGet:
    #   path: /
    #   port: http
  livenessProbe:
    # httpGet:
    #   path: /
    #   port: http
  readinessProbe:
    # httpGet:
    #   path: /
    #   port: http

  # https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 95

  # Additional volumes on the output Deployment definition.
  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  nodeSelector: {}

  tolerations: []

  affinity: {}

# backend values
backend:
  replicaCount: 1

  image:
    repository: jshimko/stack-backend
    pullPolicy: IfNotPresent
    tag: dev

  imagePullSecrets: []

  dbUrlOptions: schema=public

  # -- Backend environment variables - see available [.env](https://github.com/stack-auth/stack/blob/dev/apps/backend/.env) options
  env:
    []
    # - name: NODE_ENV
    #   value: production

  # -- Backend environment variables from secrets or configmaps
  envFrom:
    []
    # - secretRef:
    #     name: svix-jwt-secret
    # - configMapRef:
    #     name: my-configmap

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Automatically mount a ServiceAccount's API credentials?
    automount: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, name is stack-backend
    name: ""

  podAnnotations: {}
  podLabels: {}

  podSecurityContext:
    {}
    # fsGroup: 2000

  securityContext:
    {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 8102

  ingress:
    enabled: false
    className: ""
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - example.com

  # -- https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources:
    {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  startupProbe:
    # httpGet:
    #   path: /
    #   port: http
  livenessProbe:
    # httpGet:
    #   path: /
    #   port: http
  readinessProbe:
    # httpGet:
    #   path: /
    #   port: http

  # https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 95

  # -- Additional volumes on the output Deployment definition.
  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false

  # -- Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true

  nodeSelector: {}

  tolerations: []

  affinity: {}

# Postgres deployment for Stack Auth
# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
postgresql:
  enabled: true
  fullnameOverride: stack-postgresql

# Postgres auth config. See docs: https://github.com/bitnami/charts/tree/main/bitnami/postgresql
global:
  postgresql:
    auth:
      username: stack
      password: stack123
      database: stack

# -- Any misc extra K8s manifests you'd like to create
extraTemplates:
  []
  # - apiVersion: v1
  #   kind: Secret
  #   type: Opaque
  #   metadata:
  #     name: my-secret
  #     namespace: my-namespace
  #   data:
  #     key: value

# svix chart
# Optional Svix webhooks chart deployment. See docs https://github.com/jshimko/helm-charts/tree/main/charts/svix
svix:
  enabled: true

  fullnameOverride: svix

  svix:
    image:
      repository: svix/svix-server
      tag: latest
      pullPolicy: Always

    # automatically create a secret for the Svix API key so it can be mounted by the Stack backend
    # (see envFrom config in backend values above)
    createJwtSecret:
      enabled: true
      secretName: svix-jwt-secret
      secretKey: STACK_SVIX_API_KEY

    # -- Svix server config. See [docs](https://github.com/svix/svix-webhooks/blob/main/server/svix-server/config.default.toml)
    env:
      []
      # - name: SVIX_JWT_SECRET
      #   value: "change me!"
      # - name: SVIX_CACHE_TYPE
      #   value: "redis"
      # - name: SVIX_QUEUE_TYPE
      #   value: "redis"
      # - name: SVIX_ENVIRONMENT
      #   value: "prod"
      # - name: SVIX_LOG_LEVEL
      #   value: "debug"
      # - name: SVIX_WHITELABEL_HEADERS
      #   value: "true"
      # - name: WAIT_FOR
      #   value: "true"

  # Postgres deployment for Svix. See docs https://github.com/bitnami/charts/tree/main/bitnami/postgresql
  postgresql:
    enabled: true
    # -- `standalone` or `replication`
    architecture: standalone
    fullnameOverride: svix-postgresql

  # Redis deployment for Svix. See docs https://github.com/bitnami/charts/tree/main/bitnami/redis
  redis:
    enabled: true
    # -- `standalone` or `replication`
    architecture: standalone
    fullnameOverride: svix-redis
