{{- range $serviceName := list "api" "grpc" "controller" "scheduler" -}}
{{- if index $.Values $serviceName "enabled" -}}
{{- $serviceConfig := index $.Values $serviceName -}}
{{- if $serviceConfig.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hatchet.backendServiceName" (dict "serviceName" $serviceName "context" $) }}
  labels:
    {{- include "hatchet.backendServiceLabels" (dict "serviceName" $serviceName "context" $) | nindent 4 }}
  {{- with $serviceConfig.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $serviceConfig.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if $serviceConfig.ingress.tls }}
  tls:
    {{- range $serviceConfig.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $serviceConfig.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "hatchet.backendServiceName" (dict "serviceName" $serviceName "context" $) }}
                port:
                  number: {{ $serviceConfig.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
