{{- range $serviceName := list "api" "grpc" "controller" "scheduler" -}}
{{- if index $.Values $serviceName "enabled" -}}
{{- $serviceConfig := index $.Values $serviceName -}}
{{- if $serviceConfig.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hatchet.backendServiceAccountName" (dict "serviceName" $serviceName "context" $) }}
  labels:
    {{- include "hatchet.backendServiceLabels" (dict "serviceName" $serviceName "context" $) | nindent 4 }}
  {{- with $serviceConfig.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $serviceConfig.serviceAccount.automount }}
{{- end }}
{{- end }}
{{- end }}
