apiVersion: v2
name: postgrescluster
description: A Helm chart for deploying a PostgresCluster instance using Crunchy Postgres Operator. https://access.crunchydata.com/documentation/postgres-operator/latest
type: application

version: 6.0.0

# The appVersion should match the version on the PostgresCluster CRD
appVersion: 5.8.2
