{{- range $serviceName := include "services.frontendServices" $ | fromJsonArray -}}
{{- if index $.Values $serviceName "enabled" }}
{{- $serviceConfig := index $.Values $serviceName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ente-{{ include "services.frontendServiceName" (dict "serviceName" $serviceName "context" $) }}"
  labels:
    {{- include "services.frontendServiceLabels" (dict "serviceName" $serviceName "context" $) | nindent 4 }}
    {{- with $serviceConfig.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $serviceConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not $serviceConfig.autoscaling.enabled }}
  replicas: {{ $serviceConfig.replicaCount }}
  {{- end }}
  {{- with $serviceConfig.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "services.frontendServiceSelectorLabels" (dict "serviceName" $serviceName "context" $) | nindent 6 }}
  template:
    metadata:
      {{- with $serviceConfig.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "services.frontendServiceSelectorLabels" (dict "serviceName" $serviceName "context" $) | nindent 8 }}
        {{- with $serviceConfig.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "services.frontendServiceAccountName" (dict "serviceName" $serviceName "context" $) }}
      {{- with $serviceConfig.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $serviceName }}
          {{- with $serviceConfig.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ $serviceConfig.image.repository }}:{{ $serviceConfig.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $serviceConfig.image.pullPolicy | default "IfNotPresent" }}
          {{- with $serviceConfig.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $serviceConfig.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- include "services.sharedEnv" $ | nindent 12 }}
            {{- with $serviceConfig.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- include "services.sharedEnvFrom" $ | nindent 12 }}
            {{- with $serviceConfig.envFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ $serviceConfig.service.targetPort }}
              protocol: TCP
          {{- with $serviceConfig.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $serviceConfig.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $serviceConfig.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $serviceConfig.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $serviceConfig.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with $serviceConfig.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $serviceConfig.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $serviceConfig.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $serviceConfig.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $serviceConfig.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
