{{- range $serviceName := include "services.frontendServices" $ | fromJsonArray -}}
{{- if index $.Values $serviceName "enabled" -}}
{{- $serviceConfig := index $.Values $serviceName -}}
{{- if $serviceConfig.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "services.frontendServiceAccountName" (dict "serviceName" $serviceName "context" $) }}
  labels:
    {{- include "services.frontendServiceLabels" (dict "serviceName" $serviceName "context" $) | nindent 4 }}
  {{- with $serviceConfig.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $serviceConfig.serviceAccount.automount }}
{{- end }}
{{- end }}
{{- end }}
