{{- if .Values.svix.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "svix-server" .Values.svix.serviceAccount.name }}
  labels:
    {{- include "svix.labels" . | nindent 4 }}
  {{- with .Values.svix.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.svix.serviceAccount.automount }}
{{- end }}
