apiVersion: v1
kind: Service
metadata:
  name: "svix-server"
  labels:
    {{- include "svix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.svix.service.type }}
  ports:
    - port: {{ .Values.svix.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "svix.selectorLabels" . | nindent 4 }}
