apiVersion: v1
kind: Secret
metadata:
  name: stack-secrets
type: Opaque
data:
  NEXT_PUBLIC_STACK_PROJECT_ID: {{ "internal" | b64enc | quote }}
  NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  STACK_SECRET_SERVER_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  STACK_SUPER_SECRET_ADMIN_KEY: {{ randAlphaNum 32 | b64enc | quote }}
