apiVersion: v2
name: svix
description: A Helm chart for running svix on Kubernetes
type: application
version: 0.8.0

dependencies:
  # Postgres Operator - PostgresCluster
  # https://access.crunchydata.com/documentation/postgres-operator/latest/
  - name: postgrescluster
    version: 5.6.2
    repository: https://jshimko.github.io/helm-charts
    condition: postgrescluster.enabled

  # https://github.com/bitnami/charts/blob/main/bitnami/redis/Chart.yaml
  - name: redis
    version: 20.1.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
