apiVersion: v2
name: svix
description: A Helm chart for running svix on Kubernetes
type: application
version: 0.6.1

dependencies:
  # Postgres Operator - PostgresCluster
  # https://access.crunchydata.com/documentation/postgres-operator/latest/
  - name: postgrescluster
    version: 5.6.1
    repository: file://../postgrescluster
    condition: postgrescluster.enabled

  # https://github.com/bitnami/charts/blob/main/bitnami/redis/Chart.yaml
  - name: redis
    version: 20.1.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
