{{- if .Values.monitoring.serviceMonitor.enabled }}
{{- range $serviceName := list "api" "grpc" -}}
{{- if index $.Values $serviceName "enabled" -}}
{{- $serviceConfig := index $.Values $serviceName -}}
{{- if ne ($serviceConfig.service.enabled | default true) false }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "hatchet.backendServiceName" (dict "serviceName" $serviceName "context" $) }}
  labels:
    {{- include "hatchet.backendServiceLabels" (dict "serviceName" $serviceName "context" $) | nindent 4 }}
    {{- with $.Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.monitoring.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "hatchet.backendServiceSelectorLabels" (dict "serviceName" $serviceName "context" $) | nindent 6 }}
  endpoints:
    - port: http
      {{- with $.Values.monitoring.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with $.Values.monitoring.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with $.Values.monitoring.serviceMonitor.path }}
      path: {{ . }}
      {{- end }}
      {{- with $.Values.monitoring.serviceMonitor.scheme }}
      scheme: {{ . }}
      {{- end }}
      {{- with $.Values.monitoring.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.monitoring.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.monitoring.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
