{{- if .Values.jobs.quickstart.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hatchet.fullname" . }}-quickstart
  labels:
    {{- include "hatchet.labels" . | nindent 4 }}
    app.kubernetes.io/component: quickstart
  {{- with .Values.jobs.quickstart.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.jobs.quickstart.backoffLimit }}
  backoffLimit: {{ . }}
  {{- end }}
  {{- with .Values.jobs.quickstart.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ . }}
  {{- end }}
  {{- with .Values.jobs.quickstart.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.jobs.quickstart.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hatchet.labels" . | nindent 8 }}
        app.kubernetes.io/component: quickstart
        {{- with .Values.jobs.quickstart.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hatchet.fullname" . }}-quickstart
      {{- with .Values.jobs.quickstart.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.jobs.quickstart.restartPolicy }}
      containers:
        - name: quickstart
          {{- with .Values.jobs.quickstart.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.jobs.quickstart.image.repository }}:{{ .Values.jobs.quickstart.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.jobs.quickstart.image.pullPolicy }}
          {{- with .Values.jobs.quickstart.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.jobs.quickstart.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            # Set the namespace for the hatchet command to use
            - name: K8S_NAMESPACE
              value: "{{ .Release.Namespace }}"
            {{- if .Values.jobs.quickstart.useSharedEnv }}
            {{- include "hatchet.sharedEnv" . | nindent 12 }}
            {{- end }}
            {{- with .Values.jobs.quickstart.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- include "hatchet.sharedEnvFrom" . | nindent 12 }}
            {{- with .Values.jobs.quickstart.envFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.jobs.quickstart.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.jobs.quickstart.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.jobs.quickstart.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.quickstart.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.quickstart.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.quickstart.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
