{{- if .Values.jobs.seed.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hatchet.fullname" . }}-seed
  labels:
    {{- include "hatchet.labels" . | nindent 4 }}
    app.kubernetes.io/component: seed
  {{- with .Values.jobs.seed.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.jobs.seed.backoffLimit }}
  backoffLimit: {{ . }}
  {{- end }}
  {{- with .Values.jobs.seed.activeDeadlineSeconds }}
  activeDeadlineSeconds: {{ . }}
  {{- end }}
  {{- with .Values.jobs.seed.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.jobs.seed.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hatchet.labels" . | nindent 8 }}
        app.kubernetes.io/component: seed
        {{- with .Values.jobs.seed.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hatchet.fullname" . }}-seed
      {{- with .Values.jobs.seed.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.jobs.seed.restartPolicy }}
      containers:
        - name: seed
          {{- with .Values.jobs.seed.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.jobs.seed.image.repository }}:{{ .Values.jobs.seed.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.jobs.seed.image.pullPolicy }}
          {{- with .Values.jobs.seed.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.jobs.seed.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            # Set the namespace for the hatchet command to use
            - name: K8S_NAMESPACE
              value: "{{ .Release.Namespace }}"
            {{- if .Values.jobs.seed.useSharedEnv }}
            {{- include "hatchet.sharedEnv" . | nindent 12 }}
            {{- end }}
            {{- with .Values.jobs.seed.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            {{- include "hatchet.sharedEnvFrom" . | nindent 12 }}
            {{- with .Values.jobs.seed.envFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.jobs.seed.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.jobs.seed.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.jobs.seed.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.seed.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.seed.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jobs.seed.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
